version: "3"
services:
  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      #- "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
    restart: always
  nodered:
    image: nodered/node-red-docker
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
    restart: always
  thingsboard:
    image: thingsboard/tb-postgres
    ports:
      - "8080:1883"
      - "9090:9090"
      - "5683:5683"
    volumes:
      - thingsboard-data:/data
      - ./thingsboard/logs:/logs
    restart: always

volumes:
  thingsboard-data: